# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import replicacao_dados_pb2 as replicacao__dados__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in replicacao_dados_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LeaderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveData = channel.unary_unary(
                '/replicacao_dados.LeaderService/ReceiveData',
                request_serializer=replicacao__dados__pb2.Data.SerializeToString,
                response_deserializer=replicacao__dados__pb2.Ack.FromString,
                _registered_method=True)
        self.CommitData = channel.unary_unary(
                '/replicacao_dados.LeaderService/CommitData',
                request_serializer=replicacao__dados__pb2.CommitOrder.SerializeToString,
                response_deserializer=replicacao__dados__pb2.Ack.FromString,
                _registered_method=True)
        self.QueryData = channel.unary_unary(
                '/replicacao_dados.LeaderService/QueryData',
                request_serializer=replicacao__dados__pb2.QueryRequest.SerializeToString,
                response_deserializer=replicacao__dados__pb2.QueryResponse.FromString,
                _registered_method=True)


class LeaderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReceiveData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LeaderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveData': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveData,
                    request_deserializer=replicacao__dados__pb2.Data.FromString,
                    response_serializer=replicacao__dados__pb2.Ack.SerializeToString,
            ),
            'CommitData': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitData,
                    request_deserializer=replicacao__dados__pb2.CommitOrder.FromString,
                    response_serializer=replicacao__dados__pb2.Ack.SerializeToString,
            ),
            'QueryData': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryData,
                    request_deserializer=replicacao__dados__pb2.QueryRequest.FromString,
                    response_serializer=replicacao__dados__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'replicacao_dados.LeaderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('replicacao_dados.LeaderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LeaderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceiveData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replicacao_dados.LeaderService/ReceiveData',
            replicacao__dados__pb2.Data.SerializeToString,
            replicacao__dados__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replicacao_dados.LeaderService/CommitData',
            replicacao__dados__pb2.CommitOrder.SerializeToString,
            replicacao__dados__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replicacao_dados.LeaderService/QueryData',
            replicacao__dados__pb2.QueryRequest.SerializeToString,
            replicacao__dados__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReplicaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveDataFromLeader = channel.unary_unary(
                '/replicacao_dados.ReplicaService/ReceiveDataFromLeader',
                request_serializer=replicacao__dados__pb2.Data.SerializeToString,
                response_deserializer=replicacao__dados__pb2.Ack.FromString,
                _registered_method=True)
        self.CommitData = channel.unary_unary(
                '/replicacao_dados.ReplicaService/CommitData',
                request_serializer=replicacao__dados__pb2.CommitOrder.SerializeToString,
                response_deserializer=replicacao__dados__pb2.Ack.FromString,
                _registered_method=True)


class ReplicaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReceiveDataFromLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveDataFromLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveDataFromLeader,
                    request_deserializer=replicacao__dados__pb2.Data.FromString,
                    response_serializer=replicacao__dados__pb2.Ack.SerializeToString,
            ),
            'CommitData': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitData,
                    request_deserializer=replicacao__dados__pb2.CommitOrder.FromString,
                    response_serializer=replicacao__dados__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'replicacao_dados.ReplicaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('replicacao_dados.ReplicaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplicaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceiveDataFromLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replicacao_dados.ReplicaService/ReceiveDataFromLeader',
            replicacao__dados__pb2.Data.SerializeToString,
            replicacao__dados__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replicacao_dados.ReplicaService/CommitData',
            replicacao__dados__pb2.CommitOrder.SerializeToString,
            replicacao__dados__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
